site_name: PdBlog
site_author: Paddy
repo_url: https://github.com/paddywz/PdBlog
repo_name: paddywz/PdBlog

theme:
  name: material
  custom_dir: custom
  icon:
    logo: material/numeric-9-box
  features:
    - content.code.copy
    - navigation.sections
    - navigation.instant
  palette: 
    - scheme: default
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode

plugins:
  - search
  - tags
  - blog:
      blog_dir: .
      authors: true
      post_url_format: "{slug}"

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed: 
      alternate_style: true

nav:
  - index.md
